# Generated by Django 4.1.1 on 2022-10-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_version_color_delete_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpropertyvalue',
            name='property_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.propertyvalue'),
        ),
    ]
