# Generated by Django 4.1.1 on 2022-10-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productpropertyvalue_property_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_name_az',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
