# Generated by Django 4.1.1 on 2022-10-19 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_image_is_large'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_large',
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.productcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.rating'),
        ),
    ]
