# Generated by Django 4.1.1 on 2022-10-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_club_person_registrationreceipt_club_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='members',
        ),
    ]
