# Generated by Django 4.1.1 on 2022-10-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderstatus_rename_total_price_basket_item_price_and_more'),
        ('blog', '0005_remove_comment_customer_comment_user'),
        ('product', '0008_remove_review_customer_review_user'),
        ('accounts', '0002_subscriberemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
