# Generated by Django 4.1.1 on 2022-10-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberemail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
