# Generated by Django 4.1.1 on 2022-10-19 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_remove_review_customer_review_user'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('is_shipped', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='basket_item',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='basket_item',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='promocode',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='basket_item',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basket_item',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.basket'),
        ),
        migrations.AddField(
            model_name='basket_item',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productpropertyvalue'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.FloatField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.basket')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.orderstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
